services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/var/www/html
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: camagru_backend
    env_file:
      - .env
    volumes:
      - ./backend/camagru-app:/var/www/html
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: camagru_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
