services:
  php:
    build: .
    container_name: camagru_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: camagru_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8
    container_name: camagru_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
