services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/var/www/html
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: camagru_backend
    env_file:
      - .env
    volumes:
      - ./backend/camagru-app:/var/www/html
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
        mkdir -p /var/www/html/public/gallery &&
        mkdir -p /var/www/html/storage/originals &&
        chown -R www-data:www-data /var/www/html/public/gallery &&
        chmod -R 755 /var/www/html/public/gallery &&
        chown -R www-data:www-data /var/www/html/storage/originals &&
        chmod -R 755 /var/www/html/storage/originals &&
        apache2-foreground
      "
    secrets:
      - db_password
      - db_root_password

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: camagru_db
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    secrets:
      - db_password
      - db_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
